from enum import Enum


class ReasonCode(str, Enum):
    PII_EMAIL_DETECTED = "PII_EMAIL_DETECTED"
    PII_PHONE_DETECTED = "PII_PHONE_DETECTED"
    PII_RRN_DETECTED = "PII_RRN_DETECTED"
    PII_ACCOUNT_DETECTED = "PII_ACCOUNT_DETECTED"
    INJ_IGNORE_PREVIOUS_INSTRUCTIONS = "INJ_IGNORE_PREVIOUS_INSTRUCTIONS"
    INJ_REVEAL_SYSTEM_PROMPT = "INJ_REVEAL_SYSTEM_PROMPT"
    INJ_POLICY_BYPASS_ATTEMPT = "INJ_POLICY_BYPASS_ATTEMPT"
    SAFE_INPUT = "SAFE_INPUT"
